import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

const read = (path) => fs.readFileSync(path, "utf8");

test("Windows validation asserts the authoritative build identity", () => {
  const build = JSON.parse(read("build-version.json"));
  const workflow = read(".github/workflows/windows-build-1-04-validation.yml");

  assert.match(workflow, new RegExp(`name: CinaVault Premium ${build.displayName.replaceAll(".", "\\.")} Windows Validation`));
  assert.match(workflow, new RegExp(`displayName -ne '${build.displayName.replaceAll(".", "\\.")}'`));
  assert.match(workflow, new RegExp(`semanticVersion -ne '${build.semanticVersion.replaceAll(".", "\\.")}'`));
  assert.match(workflow, new RegExp(`releaseTag -ne '${build.releaseTag.replaceAll(".", "\\.")}'`));
});

test("SonarCloud analysis skips clearly unless all secret configuration exists", () => {
  const workflow = read(".github/workflows/sonarcloud.yml");

  assert.match(workflow, /SonarCloud configuration notice/);
  assert.match(workflow, /SONAR_TOKEN: \$\{\{ secrets\.SONAR_TOKEN \}\}/);
  assert.match(workflow, /SONAR_PROJECT_KEY: \$\{\{ vars\.SONAR_PROJECT_KEY \}\}/);
  assert.match(workflow, /SONAR_ORGANIZATION: \$\{\{ vars\.SONAR_ORGANIZATION \}\}/);
  assert.match(workflow, /if: \$\{\{ !secrets\.SONAR_TOKEN \|\| !vars\.SONAR_PROJECT_KEY \|\| !vars\.SONAR_ORGANIZATION \}\}/);
  assert.match(workflow, /if: \$\{\{ secrets\.SONAR_TOKEN && vars\.SONAR_PROJECT_KEY && vars\.SONAR_ORGANIZATION \}\}/);
  assert.match(workflow, /::notice title=SonarCloud skipped/);
  assert.doesNotMatch(workflow, /-Dsonar\.(?:projectKey|organization)=\s*$/m);
});

test("Cargo lockfile is reproducible UTF-8 TOML", () => {
  const lockfile = read("src-tauri/Cargo.lock");

  assert.match(lockfile, /^# This file is automatically @generated by Cargo\./);
  assert.match(lockfile, /^version = 4$/m);
  assert.match(lockfile, /^\[\[package\]\]$/m);
});
