#!/usr/bin/env node
/**
 * CinaVault Premium — Automated Post-Build Cleanup & Organization
 * Build 155+
 *
 * Runs after every successful build to:
 *  1. Remove build artifacts and temp files
 *  2. Remove empty directories
 *  3. Remove duplicate/orphaned CSS files
 *  4. Remove unreferenced static assets
 *  5. Remove stale test fixtures
 *  6. Auto-format all source files (Prettier + rustfmt)
 *  7. Report every action taken to stdout and write a cleanup log
 *
 * Usage:
 *   node scripts/cleanup.mjs [--dry-run] [--verbose]
 *
 * Options:
 *   --dry-run   Print what would be removed/changed without doing it
 *   --verbose   Print every file checked, not just actions taken
 */

import fs from "fs";
import path from "path";
import { execSync, spawnSync } from "child_process";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

const DRY_RUN = process.argv.includes("--dry-run");
const VERBOSE = process.argv.includes("--verbose");

const log = (msg) => console.log(`[cleanup] ${msg}`);
const verbose = (msg) => { if (VERBOSE) console.log(`[cleanup:verbose] ${msg}`); };
const warn = (msg) => console.warn(`[cleanup:warn] ${msg}`);

const actions = [];
const record = (action, target, reason) => {
  actions.push({ action, target, reason });
  log(`${DRY_RUN ? "[DRY-RUN] " : ""}${action}: ${target} — ${reason}`);
};

// ─── Helpers ────────────────────────────────────────────────────────────────

function rmdirIfEmpty(dir) {
  if (!fs.existsSync(dir)) return;
  const entries = fs.readdirSync(dir);
  if (entries.length === 0) {
    record("REMOVE_EMPTY_DIR", path.relative(ROOT, dir), "empty directory");
    if (!DRY_RUN) fs.rmdirSync(dir);
  }
}

function removeFile(filePath, reason) {
  if (!fs.existsSync(filePath)) return;
  record("REMOVE_FILE", path.relative(ROOT, filePath), reason);
  if (!DRY_RUN) fs.rmSync(filePath, { force: true });
}

function removeGlob(dir, patterns, reason) {
  if (!fs.existsSync(dir)) return;
  const walk = (d) => {
    for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
      const full = path.join(d, entry.name);
      if (entry.isDirectory()) {
        walk(full);
      } else {
        const rel = path.relative(ROOT, full);
        for (const pat of patterns) {
          if (typeof pat === "string" ? entry.name === pat : pat.test(entry.name)) {
            record("REMOVE_FILE", rel, reason);
            if (!DRY_RUN) fs.rmSync(full, { force: true });
            break;
          }
        }
      }
    }
  };
  walk(dir);
}

function runCmd(cmd, cwd = ROOT) {
  if (DRY_RUN) {
    log(`[DRY-RUN] Would run: ${cmd}`);
    return;
  }
  try {
    execSync(cmd, { cwd, stdio: "pipe" });
    log(`Ran: ${cmd}`);
  } catch (e) {
    warn(`Command failed (non-fatal): ${cmd}\n  ${e.message}`);
  }
}

// ─── 1. Build artifacts & temp files ────────────────────────────────────────

log("=== Step 1: Removing build artifacts and temp files ===");

const ARTIFACT_DIRS = [
  "dist",
  "src-tauri/target/debug",
  "src-tauri/target/x86_64-pc-windows-msvc/debug",
];
const ARTIFACT_FILE_PATTERNS = [
  /\.tmp$/,
  /\.log$/,
  /~$/,
  /\.bak$/,
  /\.orig$/,
  /\.swp$/,
  /Thumbs\.db$/,
  /\.DS_Store$/,
];

// Only clean dist if we're post-build (dist is re-generated by build)
const distDir = path.join(ROOT, "dist");
if (fs.existsSync(distDir)) {
  record("REMOVE_DIR", "dist", "stale build output — will be regenerated on next build");
  if (!DRY_RUN) fs.rmSync(distDir, { recursive: true, force: true });
}

// Remove stray temp/log files in src tree (not in node_modules or target)
removeGlob(path.join(ROOT, "src"), ARTIFACT_FILE_PATTERNS, "temp/backup file in src tree");
removeGlob(path.join(ROOT, "src-tauri", "src"), ARTIFACT_FILE_PATTERNS, "temp/backup file in Rust src tree");
removeGlob(path.join(ROOT, "tests"), ARTIFACT_FILE_PATTERNS, "temp file in tests directory");
removeGlob(path.join(ROOT, "scripts"), ARTIFACT_FILE_PATTERNS, "temp file in scripts directory");

// ─── 2. Empty directories ────────────────────────────────────────────────────

log("=== Step 2: Removing empty directories ===");

const SCAN_DIRS = ["src", "src-tauri/src", "tests", "scripts", "docs", "public"];
for (const d of SCAN_DIRS) {
  const full = path.join(ROOT, d);
  if (!fs.existsSync(full)) continue;
  // Walk depth-first to catch nested empties
  const walkEmpty = (dir) => {
    if (!fs.existsSync(dir)) return;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) walkEmpty(path.join(dir, entry.name));
    }
    rmdirIfEmpty(dir);
  };
  walkEmpty(full);
}

// ─── 3. Duplicate / orphaned CSS files ──────────────────────────────────────

log("=== Step 3: Checking for duplicate/orphaned CSS files ===");

// Known superseded CSS files that have been replaced by consolidated versions
const SUPERSEDED_CSS = [
  "src/styles/media-card-hard-fix.css",   // superseded by kodi-skin.css + main styles
  "src/styles/media-row-poster-final-fix.css", // superseded by kodi-skin.css
];

// Check if each superseded file is still imported anywhere; if not, remove it
for (const cssRel of SUPERSEDED_CSS) {
  const cssAbs = path.join(ROOT, cssRel);
  if (!fs.existsSync(cssAbs)) {
    verbose(`Already absent: ${cssRel}`);
    continue;
  }
  const cssBasename = path.basename(cssRel);
  // Search for imports in src tree
  let imported = false;
  const searchDirs = ["src", "client/src"];
  for (const sd of searchDirs) {
    const sdAbs = path.join(ROOT, sd);
    if (!fs.existsSync(sdAbs)) continue;
    try {
      const result = spawnSync("grep", ["-r", "--include=*.ts", "--include=*.tsx", "--include=*.css", "-l", cssBasename, sdAbs], { encoding: "utf8" });
      if (result.stdout && result.stdout.trim()) {
        imported = true;
        verbose(`${cssRel} is imported in: ${result.stdout.trim()}`);
        break;
      }
    } catch (_) {}
  }
  if (!imported) {
    removeFile(cssAbs, "orphaned CSS — not imported anywhere in src tree");
  }
}

// ─── 4. Stale test fixtures ──────────────────────────────────────────────────

log("=== Step 4: Removing stale test fixtures ===");

const FIXTURE_DIR = path.join(ROOT, "tests", "fixtures");
if (fs.existsSync(FIXTURE_DIR)) {
  // Remove any fixture files older than 30 days that are not referenced in test files
  const fixtureFiles = fs.readdirSync(FIXTURE_DIR).filter(f => !f.startsWith("."));
  for (const fixture of fixtureFiles) {
    const fixturePath = path.join(FIXTURE_DIR, fixture);
    const stat = fs.statSync(fixturePath);
    const ageMs = Date.now() - stat.mtimeMs;
    const ageDays = ageMs / (1000 * 60 * 60 * 24);
    if (ageDays > 30) {
      // Check if referenced in any test file
      const result = spawnSync("grep", ["-r", "--include=*.mjs", "--include=*.ts", "-l", fixture, path.join(ROOT, "tests")], { encoding: "utf8" });
      if (!result.stdout || !result.stdout.trim()) {
        removeFile(fixturePath, `stale fixture — ${Math.floor(ageDays)} days old, not referenced in tests`);
      }
    }
  }
}

// ─── 5. Unreferenced static assets ──────────────────────────────────────────

log("=== Step 5: Checking for unreferenced static assets ===");

const ASSET_DIRS = ["public", "src/assets"];
const ASSET_EXTENSIONS = [".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp", ".ico"];

for (const assetDirRel of ASSET_DIRS) {
  const assetDirAbs = path.join(ROOT, assetDirRel);
  if (!fs.existsSync(assetDirAbs)) continue;

  const assetFiles = fs.readdirSync(assetDirAbs, { withFileTypes: true })
    .filter(e => e.isFile() && ASSET_EXTENSIONS.some(ext => e.name.endsWith(ext)));

  for (const asset of assetFiles) {
    const assetName = asset.name;
    // Skip favicon and known required assets
    if (["favicon.ico", "favicon.png", "cinavault-logo.png", "icon.png", "icon.ico"].includes(assetName)) {
      verbose(`Skipping required asset: ${assetName}`);
      continue;
    }
    // Search for references in src tree
    const result = spawnSync("grep", ["-r", "--include=*.ts", "--include=*.tsx", "--include=*.css", "--include=*.html", "-l", assetName, path.join(ROOT, "src")], { encoding: "utf8" });
    if (!result.stdout || !result.stdout.trim()) {
      // Also check client/src if it exists
      const result2 = spawnSync("grep", ["-r", "--include=*.ts", "--include=*.tsx", "--include=*.css", "--include=*.html", "-l", assetName, path.join(ROOT, "client")], { encoding: "utf8" });
      if (!result2.stdout || !result2.stdout.trim()) {
        warn(`Unreferenced asset (not removed — manual review needed): ${assetDirRel}/${assetName}`);
        // We warn but do not auto-remove assets — too risky without human confirmation
      }
    }
  }
}

// ─── 6. Auto-format source files ────────────────────────────────────────────

log("=== Step 6: Auto-formatting source files ===");

// Prettier for TypeScript/CSS/JSON
if (!DRY_RUN) {
  runCmd("npx prettier --write 'src/**/*.{ts,tsx,css,json}' --log-level warn", ROOT);
  runCmd("npx prettier --write 'tests/**/*.mjs' --log-level warn", ROOT);
  runCmd("npx prettier --write 'package.json' --log-level warn", ROOT);
}

// rustfmt for Rust source
if (!DRY_RUN) {
  runCmd("cargo fmt --manifest-path src-tauri/Cargo.toml", ROOT);
}

// ─── 7. Remove dead TypeScript exports (report only) ────────────────────────

log("=== Step 7: Dead export detection (report only — no auto-removal) ===");

// Use ts-prune if available, otherwise skip
try {
  const tsPrune = spawnSync("npx", ["ts-prune", "--error"], { cwd: ROOT, encoding: "utf8" });
  if (tsPrune.stdout && tsPrune.stdout.trim()) {
    log("Dead exports detected (review and remove manually):");
    tsPrune.stdout.trim().split("\n").forEach(line => log(`  ${line}`));
  } else {
    log("No dead exports detected.");
  }
} catch (_) {
  verbose("ts-prune not available — skipping dead export check");
}

// ─── 8. Organize docs directory ─────────────────────────────────────────────

log("=== Step 8: Organizing docs directory ===");

const docsDir = path.join(ROOT, "docs");
if (!fs.existsSync(docsDir)) {
  if (!DRY_RUN) fs.mkdirSync(docsDir, { recursive: true });
  log("Created docs/ directory");
}

// Move any release notes from root into docs/releases/
const releasesDir = path.join(docsDir, "releases");
if (!fs.existsSync(releasesDir) && !DRY_RUN) {
  fs.mkdirSync(releasesDir, { recursive: true });
}

const rootFiles = fs.readdirSync(ROOT, { withFileTypes: true });
for (const entry of rootFiles) {
  if (!entry.isFile()) continue;
  if (/^RELEASE_NOTES_BUILD\d+\.md$/.test(entry.name)) {
    const src = path.join(ROOT, entry.name);
    const dest = path.join(releasesDir, entry.name);
    if (!fs.existsSync(dest)) {
      record("MOVE_FILE", `${entry.name} → docs/releases/${entry.name}`, "organizing release notes into docs/releases/");
      if (!DRY_RUN) fs.renameSync(src, dest);
    }
  }
}

// ─── 9. Write cleanup report ────────────────────────────────────────────────

log("=== Step 9: Writing cleanup report ===");

const reportDir = path.join(docsDir, "cleanup-reports");
if (!fs.existsSync(reportDir) && !DRY_RUN) {
  fs.mkdirSync(reportDir, { recursive: true });
}

const now = new Date().toISOString().replace(/[:.]/g, "-");
const reportPath = path.join(reportDir, `cleanup-${now}.md`);
const reportLines = [
  `# CinaVault Premium — Cleanup Report`,
  ``,
  `**Date:** ${new Date().toISOString()}`,
  `**Mode:** ${DRY_RUN ? "DRY RUN" : "LIVE"}`,
  `**Actions taken:** ${actions.length}`,
  ``,
  `## Actions`,
  ``,
  `| Action | Target | Reason |`,
  `|--------|--------|--------|`,
  ...actions.map(a => `| ${a.action} | \`${a.target}\` | ${a.reason} |`),
  ``,
  `---`,
  `*Generated by scripts/cleanup.mjs*`,
];

if (!DRY_RUN) {
  fs.writeFileSync(reportPath, reportLines.join("\n"), "utf8");
  log(`Cleanup report written: ${path.relative(ROOT, reportPath)}`);
} else {
  log(`[DRY-RUN] Would write cleanup report to: ${path.relative(ROOT, reportPath)}`);
}

log(`=== Cleanup complete. ${actions.length} action(s) taken. ===`);
if (actions.length === 0) log("Repository is clean — nothing to remove or reorganize.");

process.exit(0);
